[build]
  publish = "/"
  
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "ALLOW"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'self' https://dashboard.pixelnest.ai;"